version: "3.8"
services:
  db:
    image: postgres
    env_file:
      - 'postgres_env_vars.env'
    volumes:
      - ~/postgres-space/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  telegram-bot:
    image: python:latest
    env_file:
      - 'postgres_env_vars.env'
      - 'telegram_env_vars.env'
    build: .
    depends_on:
      - "db"
    command: ["./wait-for-it.sh", "db:5432", "-t", "300", "--", "python", "./bot.py"]

